name: bugetbuddy
description: Um app para lhe ajudar financeiramente.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.19
  font_awesome_flutter: ^10.4.0
  google_sign_in: ^6.1.2
  http: ^0.13.5
  provider: ^6.0.5
  unicons: ^2.1.1
  uuid: ^3.0.7

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/welcome.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#cdffd8"
  adaptive_icon_foreground: "assets/icon-nobg.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/icon-nobg.png
    - assets/welcome.png
