// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcfxi8uYhJOG7vaHoZ8JN0xCHF6XAz6UE',
    appId: '1:947891333173:android:0a5b24c35e757d0745697c',
    messagingSenderId: '947891333173',
    projectId: 'buget-buddy',
    databaseURL: 'https://buget-buddy-default-rtdb.firebaseio.com',
    storageBucket: 'buget-buddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzRQA_7sMybScgHQ1UAKxLtt4I_tR-bA',
    appId: '1:947891333173:ios:0ef25b8f17c9fe7145697c',
    messagingSenderId: '947891333173',
    projectId: 'buget-buddy',
    databaseURL: 'https://buget-buddy-default-rtdb.firebaseio.com',
    storageBucket: 'buget-buddy.appspot.com',
    iosClientId: '947891333173-93n0sa0bv86apm5l3fmeolcbamnm8pbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.bugetbuddy',
  );
}
